### ISSUE TITLE
En-Ro does not display correctly 

### ISSUE THREAD

**Issue by ghost** [KuromeSan/ValkyrieStore#2]
Also Romanian Store not working/displaying correctly 

https://store.playstation.com/en-ro/home/games

**Comment by LiEnby** [comment]
oof- ro-ro has 0 files archived ... that will be hard ...
en-ro has one but its an older version

**Comment by ghost** [comment]
Yeah, i've noticed browsing on the wayback machine. Maybe that one en-ro could be used? Realistically, I'm using this to grab PSN links from PS Store, as the method required the account to be signed in

**Comment by LiEnby** [comment]
hm, another option is to craft a sort of "all-regions" html file and just load it everywhere.

**Comment by ghost** [comment]
Yeah, maybe that could work. The PSN thing needs to be logged in the old store to so that this link would not display session expired: 
https://store.playstation.com/kamaji/api/chihiro/00_09_000/gateway/store/v1/users/me/internal_entitlements?start=0&size=15000&fields=game_meta%2Cdrm_def

**Comment by LiEnby** [comment]
login at my.playstation.com, then load the store it really works xD

btw- updated to 1.2 which has a universal loader for all regions xD

**Comment by ghost** [comment]
Alright, testing rn, in a moment

**Comment by ghost** [comment]
Nope, wont budge, loading the store asks me to proceed to Romania - English store (en-ro) and auto redirects to /latest page (including typing en-ro in the /home/games link)

**Comment by ghost** [comment]
Edit: typing ro-ro does fix the redirect. Got it now

**Comment by LiEnby** [comment]
i dont think ro-ro exists, since it seems to redirect to whatever the last page you were on was xD

**Comment by LiEnby** [comment]
https://store.playstation.com/en-ro/home/games this works for me thou

**Comment by LiEnby** [comment]
providing im not logged into my main account which is not romanian nyway

**Comment by ghost** [comment]
Huh, now it randomly worked, thats odd. It did not work before tho lol

**Comment by LiEnby** [comment]
k closing this,
