### ISSUE TITLE
req - fix readme how to build xpi

### ISSUE THREAD

**Issue by tomazzz369z** [KuromeSan/ValkyrieStore#4]
i tried to build plugin to work with older firefox 52.9.0, but this trick with zipping files not working, firefox constantly says file is corrupted, probably because file is not signed - there is no META-INF dir and i have no idea how to sign plugin, could you fix readme

regards and thanks

**Comment by LiEnby** [comment]
XPI Extensions have to be signed by mozilla in order for them to work in the normal mozilla firefox-

https://extensionworkshop.com/documentation/publish/signing-and-distribution-overview/#distributing-your-addon

u can load unsigned extensions using Firefox Developer Edition and changing some flags in about:config.
and u can load them temporarily by clicking the settings cog thing and doing "Debug Add Ons" then "Load Extension" where it'll work until u restart the browser.
