### ISSUE TITLE
GTA Vice City Stories PSN

### ISSUE THREAD

**Issue by Alex-Vaduva** [KuromeSan/ValkyrieStore#5]
Hi,

Currently when I access https://store.playstation.com/en-us/product/UP9000-NPUD21590_00-0000000000000000, I can't buy it. This is because at the beginning of 2018 it was removed from PSN. Is it possible for the Valkyrie Store to display the game when it could been bought and see if it can be purchased?

Thanks,
Alex

**Comment by LiEnby** [comment]
if its removed / delisted from the store then i cant get it to show up ... its not a problem with me.
